# Generated by Django 5.1.3 on 2024-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
