# Generated by Django 5.1.3 on 2024-11-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_filestorage_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(blank=True, max_length=128, null=True)),
                ('condition', models.CharField(blank=True, max_length=3, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('column_2', models.CharField(blank=True, max_length=128, null=True)),
                ('search', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analysis.filestorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
