# Generated by Django 5.1.3 on 2024-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_history_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='type',
            field=models.CharField(choices=[('csv', 'CSV')], max_length=5),
        ),
    ]
